<div class="container-fluid">
	<div class="row">
		<div class="col-md-2">
			<div class="list-group">
				<a data-ui-sref="app.dashboard" class="list-group-item" data-ui-sref-active="active">DashBoard</a>
				<a data-ui-sref="app.read-web" class="list-group-item" data-ui-sref-active="active">Leer Datos</a>
				<a data-ui-sref="app.geocode" class="list-group-item" data-ui-sref-active="active">Geocode</a>
				
			</div>
		</div>
		<div class="col-md-10">
			<div ui-view></div>
		</div>
	</div>
</div>
