<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Admin\Module'                         => __DIR__ . '/Module.php',
    //'Admin\Controller\AccountController'   => __DIR__ . '/src/Admin/Controller/AccountController.php',
    //'Admin\Controller\BaseController'      => __DIR__ . '/src/Admin/Controller/BaseController.php',
    //'Admin\Controller\DashboardController' => __DIR__ . '/src/Admin/Controller/DashboardController.php',
    //'Admin\Controller\SisController'       => __DIR__ . '/src/Admin/Controller/SisController.php',
    //'Admin\View\Helper\AdminMenu'          => __DIR__ . '/src/Admin/View/Helper/AdminMenu.php',
);
